import '../models/data_models.dart';

class MockRepository {
  static UserModel currentUser = UserModel(
    id: 'user_uid_123',
    name: 'Kaju Sharma',
    email: 'kaju.sharma@hiregrid.com',
    role: 'student',
    branchId: 'branch_cse_101',
    branch: 'Computer Science Engineering',
    college: 'Marwadi University',
    university: 'GTU',
    activePlanId: 'plan_gold_999',
    planExpiry: DateTime.now().add(const Duration(days: 90)).millisecondsSinceEpoch,
    xp: 1450,
    streak: 7,
    accuracy: 82.5,
    lastExamAttemptDate: '2026-09-05',
    moduleScores: {
      'mod_trees_01': 85,
      'mod_tcs_nqt': 90,
      'mod_dbms_01': 55,
    },
    grantedModuleAccess: {
      'mod_tcs_nqt': 1789000000000,
    },
    theme: 'dark',
  );

  static List<HierarchyNode> subjects = [
    HierarchyNode(
      id: 'sub_dsa',
      name: 'Data Structures & Algorithms',
      type: 'subject',
      parentId: 'branch_cse_101',
      accessType: 'free',
      displayOrder: 1,
      moduleCount: 12,
      progress: 0.65,
    ),
    HierarchyNode(
      id: 'sub_dbms',
      name: 'Database Management Systems',
      type: 'subject',
      parentId: 'branch_cse_101',
      accessType: 'free',
      displayOrder: 2,
      moduleCount: 8,
      progress: 0.40,
    ),
    HierarchyNode(
      id: 'sub_os',
      name: 'Operating Systems',
      type: 'subject',
      parentId: 'branch_cse_101',
      accessType: 'free',
      displayOrder: 3,
      moduleCount: 10,
      progress: 0.80,
    ),
    HierarchyNode(
      id: 'sub_cn',
      name: 'Computer Networks',
      type: 'subject',
      parentId: 'branch_cse_101',
      accessType: 'premium_only',
      displayOrder: 4,
      moduleCount: 9,
      progress: 0.20,
    ),
    HierarchyNode(
      id: 'sub_aptitude',
      name: 'Quantitative Aptitude',
      type: 'subject',
      parentId: 'branch_cse_101',
      accessType: 'free',
      displayOrder: 5,
      moduleCount: 15,
      progress: 0.50,
    ),
  ];

  static List<HierarchyNode> getTopicsForSubject(String subjectId) {
    if (subjectId == 'sub_dsa') {
      return [
        HierarchyNode(
          id: 'topic_trees',
          name: 'Trees & Graphs',
          type: 'topic',
          parentId: 'sub_dsa',
          accessType: 'free',
          displayOrder: 1,
          moduleCount: 4,
          progress: 0.75,
        ),
        HierarchyNode(
          id: 'topic_sorting',
          name: 'Sorting & Searching',
          type: 'topic',
          parentId: 'sub_dsa',
          accessType: 'free',
          displayOrder: 2,
          moduleCount: 3,
          progress: 0.50,
        ),
        HierarchyNode(
          id: 'topic_dp',
          name: 'Dynamic Programming',
          type: 'topic',
          parentId: 'sub_dsa',
          accessType: 'premium_only',
          displayOrder: 3,
          moduleCount: 5,
          progress: 0.0,
        ),
      ];
    }
    return [
      HierarchyNode(
        id: 'topic_gen',
        name: 'Core Concepts',
        type: 'topic',
        parentId: subjectId,
        accessType: 'free',
        displayOrder: 1,
        moduleCount: 4,
        progress: 0.40,
      ),
    ];
  }

  static ExamModule dsaTreesExam = ExamModule(
    id: 'mod_trees_01',
    title: 'Binary Trees & BST Assessment',
    parentId: 'topic_trees',
    category: 'Data Structures',
    timeLimitMinutes: 30,
    passPercentage: 60,
    accessType: 'free',
    lastScore: 85,
    questions: [
      ExamQuestion(
        id: 'q1',
        text: 'What is the maximum number of nodes at level L in a binary tree?',
        options: ['2^(L-1)', '2^L', '2^(L+1)', '2^L - 1'],
        correctOptionIndex: 1,
        explanation: 'In a binary tree, the maximum number of nodes at level L is 2^L (assuming root is at level 0).',
      ),
      ExamQuestion(
        id: 'q2',
        text: 'What is the time complexity of searching for an element in a balanced Binary Search Tree (BST)?',
        options: ['O(1)', 'O(log N)', 'O(N)', 'O(N log N)'],
        correctOptionIndex: 1,
        explanation: 'A balanced BST eliminates half the remaining nodes at each step, resulting in O(log N) time complexity.',
      ),
      ExamQuestion(
        id: 'q3',
        text: 'Which traversal technique produces sorted output for a Binary Search Tree?',
        options: ['Pre-order', 'In-order', 'Post-order', 'Level-order'],
        correctOptionIndex: 1,
        explanation: 'In-order traversal visits left subtree, root, then right subtree, which naturally sorts BST elements.',
      ),
      ExamQuestion(
        id: 'q4',
        text: 'What is the height of a balanced BST with N nodes?',
        options: ['O(N)', 'O(log N)', 'O(N^2)', 'O(1)'],
        correctOptionIndex: 1,
        explanation: 'A balanced tree maintains a height bounded logarithmically relative to node count N.',
      ),
      ExamQuestion(
        id: 'q5',
        text: 'In a complete binary tree of height H, what is the minimum number of nodes?',
        options: ['2^H', '2^(H-1) + 1', '2^(H+1) - 1', 'H^2'],
        correctOptionIndex: 0,
        explanation: 'At minimum height H, all levels up to H-1 are full plus at least 1 node at level H.',
      ),
    ],
  );

  static List<CompanyModel> companies = [
    CompanyModel(
      id: 'comp_tcs',
      name: 'TCS',
      logoUrl: 'assets/companies/tcs.png',
      accessBadge: 'UNLOCKED',
      price: '₹149',
      description: 'Tata Consultancy Services NQT & Ninja / Digital assessment modules.',
      minCgpa: '60% or 6.0 CGPA',
      eligibleBranches: 'CSE / IT / ECE / EEE / ME',
      backlogsPolicy: 'Max 1 active backlog at selection',
      modules: [
        ExamModule(
          id: 'mod_tcs_nqt',
          title: 'TCS NQT Aptitude & Logic Mock',
          parentId: 'comp_tcs',
          category: 'Company Test',
          timeLimitMinutes: 45,
          passPercentage: 70,
          accessType: 'free',
          lastScore: 90,
          questions: [],
        ),
        ExamModule(
          id: 'mod_tcs_coding',
          title: 'TCS Ninja Coding Fundamentals',
          parentId: 'comp_tcs',
          category: 'Company Test',
          timeLimitMinutes: 30,
          passPercentage: 60,
          accessType: 'free',
          questions: [],
        ),
      ],
    ),
    CompanyModel(
      id: 'comp_infosys',
      name: 'Infosys',
      logoUrl: 'assets/companies/infosys.png',
      accessBadge: 'FREE',
      price: 'Free',
      description: 'Infosys Specialist Programmer & System Engineer mock tests.',
      minCgpa: '65% overall academic record',
      eligibleBranches: 'All B.Tech / M.Tech / MCA',
      backlogsPolicy: 'No active backlogs allowed',
      modules: [
        ExamModule(
          id: 'mod_infy_1',
          title: 'Infosys Mathematical & Reasoning Test',
          parentId: 'comp_infosys',
          category: 'Company Test',
          timeLimitMinutes: 40,
          passPercentage: 65,
          accessType: 'free',
          questions: [],
        ),
      ],
    ),
    CompanyModel(
      id: 'comp_wipro',
      name: 'Wipro',
      logoUrl: 'assets/companies/wipro.png',
      accessBadge: 'PREMIUM',
      price: '₹199',
      description: 'Wipro NLTH National Talent Hunt Assessment.',
      minCgpa: '60% throughout 10th, 12th & Graduation',
      eligibleBranches: 'CSE / IT / ECE / EEE',
      backlogsPolicy: 'No active backlogs',
      modules: [],
    ),
    CompanyModel(
      id: 'comp_lt',
      name: 'L&T',
      logoUrl: 'assets/companies/lt.png',
      accessBadge: 'PREMIUM',
      price: '₹249',
      description: 'Larsen & Toubro Technical & General Ability Test.',
      minCgpa: '65% / 6.75 CGPA',
      eligibleBranches: 'Civil / Mechanical / Electrical / CSE',
      backlogsPolicy: 'Zero backlogs allowed',
      modules: [],
    ),
    CompanyModel(
      id: 'comp_reliance',
      name: 'Reliance',
      logoUrl: 'assets/companies/reliance.png',
      accessBadge: 'UNLOCKED',
      price: '₹149',
      description: 'Reliance Industries Graduate Engineer Trainee Assessment.',
      minCgpa: '60% minimum',
      eligibleBranches: 'All Engineering Disciplines',
      backlogsPolicy: 'No backlogs during join',
      modules: [],
    ),
    CompanyModel(
      id: 'comp_maruti',
      name: 'Maruti Suzuki',
      logoUrl: 'assets/companies/maruti.png',
      accessBadge: 'PREMIUM',
      price: '₹299',
      description: 'Maruti Suzuki Core Technical & Engineering Test.',
      minCgpa: '70% / 7.0 CGPA',
      eligibleBranches: 'Mechanical / Electrical / CSE / Automobile',
      backlogsPolicy: 'Strictly zero backlogs',
      modules: [],
    ),
  ];

  static List<PlanModel> plans = [
    PlanModel(
      id: 'plan_1m',
      title: '1 Month Explorer',
      durationText: '1 Month',
      priceText: '₹249',
      benefits: [
        'Access to all subject learning nodes',
        'Basic company prep tests',
        'Standard solution explanations',
      ],
    ),
    PlanModel(
      id: 'plan_3m',
      title: '3 Months Pro Prep',
      durationText: '3 Months',
      priceText: '₹599',
      isPopular: true,
      benefits: [
        'Full Subject & Learning Hierarchy',
        'All Tier-1 Company Exam Prep',
        'Weekly Placement Mission Entry',
        'Detailed Step-by-Step Solutions',
        'Global Leaderboard Access',
      ],
    ),
    PlanModel(
      id: 'plan_6m',
      title: '6 Months Mastery',
      durationText: '6 Months',
      priceText: '₹999',
      benefits: [
        'Everything in 3 Months Pro Plan',
        'Priority Doubt Support',
        'Mock Interview Preparation Guides',
        'Resume & ATS Score Review',
      ],
    ),
    PlanModel(
      id: 'plan_12m',
      title: '12 Months Placement Guarantee',
      durationText: '12 Months',
      priceText: '₹1499',
      benefits: [
        'Lifetime update access for 1 full year',
        'Exclusive Premium Mentor Sessions',
        'Unlimited Mock Assessments',
        'Direct Campus Referral Badge',
      ],
    ),
  ];

  static List<LeaderboardUser> leaderboard = [
    LeaderboardUser(rank: 1, name: 'Aarav Patel', branch: 'CSE - Marwadi Univ', xp: 2840, avatarUrl: ''),
    LeaderboardUser(rank: 2, name: 'Priya Sharma', branch: 'IT - Nirma Univ', xp: 2610, avatarUrl: ''),
    LeaderboardUser(rank: 3, name: 'Rohan Mehta', branch: 'ECE - GTU', xp: 2450, avatarUrl: ''),
    LeaderboardUser(rank: 4, name: 'Ananya Gupta', branch: 'CSE - MSU Baroda', xp: 2190, avatarUrl: ''),
    LeaderboardUser(rank: 5, name: 'Kaju Sharma', branch: 'MCA - Marwadi Univ', xp: 1450, avatarUrl: ''),
    LeaderboardUser(rank: 6, name: 'Vikram Singh', branch: 'ME - LD College', xp: 1320, avatarUrl: ''),
    LeaderboardUser(rank: 7, name: 'Sneha Roy', branch: 'CSE - PDEU', xp: 1180, avatarUrl: ''),
  ];
}
